{
	"cve": {
		"CVE_data_meta": {
			"ASSIGNER": "cve@mitre.org",
			"ID": "CVE-2023-44271"
		},
		"data_format": "MITRE",
		"data_type": "CVE",
		"data_version": "4.0",
		"description": {
			"description_data": [
				{
					"lang": "en",
					"value": "An issue was discovered in Pillow before 10.0.0. It is a Denial of Service that uncontrollably allocates memory to process a given task, potentially causing a service to crash by having it run out of memory. This occurs for truetype in ImageFont when textlength in an ImageDraw instance operates on a long text argument."
				}
			]
		},
		"problemtype": {
			"problemtype_data": [
				{
					"description": [
						{
							"lang": "en",
							"value": "CWE-770"
						}
					]
				}
			]
		},
		"references": {
			"reference_data": [
				{
					"name": "https://devhub.checkmarx.com/cve-details/CVE-2023-44271/",
					"tags": [
						"Third Party Advisory"
					],
					"url": "https://devhub.checkmarx.com/cve-details/CVE-2023-44271/"
				},
				{
					"name": "https://devhub.checkmarx.com/cve-details/CVE-2023-44271/",
					"tags": [
						"Third Party Advisory"
					],
					"url": "https://devhub.checkmarx.com/cve-details/CVE-2023-44271/"
				},
				{
					"name": "https://github.com/python-pillow/Pillow/commit/1fe1bb49c452b0318cad12ea9d97c3bef188e9a7",
					"tags": [
						"Patch"
					],
					"url": "https://github.com/python-pillow/Pillow/commit/1fe1bb49c452b0318cad12ea9d97c3bef188e9a7"
				},
				{
					"name": "https://github.com/python-pillow/Pillow/commit/1fe1bb49c452b0318cad12ea9d97c3bef188e9a7",
					"tags": [
						"Patch"
					],
					"url": "https://github.com/python-pillow/Pillow/commit/1fe1bb49c452b0318cad12ea9d97c3bef188e9a7"
				},
				{
					"name": "https://github.com/python-pillow/Pillow/pull/7244",
					"tags": [
						"Patch"
					],
					"url": "https://github.com/python-pillow/Pillow/pull/7244"
				},
				{
					"name": "https://github.com/python-pillow/Pillow/pull/7244",
					"tags": [
						"Patch"
					],
					"url": "https://github.com/python-pillow/Pillow/pull/7244"
				},
				{
					"name": "[debian-lts-announce] 20240322 [SECURITY] [DLA 3768-1] pillow security update",
					"url": "https://lists.debian.org/debian-lts-announce/2024/03/msg00021.html"
				},
				{
					"name": "[debian-lts-announce] 20240322 [SECURITY] [DLA 3768-1] pillow security update",
					"url": "https://lists.debian.org/debian-lts-announce/2024/03/msg00021.html"
				},
				{
					"name": "FEDORA-2023-1a120657f9",
					"tags": [
						"Mailing List",
						"Third Party Advisory"
					],
					"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/N2JOEDUJDQLCUII2LQYZYSM7RJL2I3P4/"
				},
				{
					"name": "FEDORA-2023-1a120657f9",
					"tags": [
						"Mailing List",
						"Third Party Advisory"
					],
					"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/N2JOEDUJDQLCUII2LQYZYSM7RJL2I3P4/"
				}
			]
		}
	},
	"impact": {
		"baseMetricV3": {
			"cvssV3": {
				"attackComplexity": "LOW",
				"attackVector": "NETWORK",
				"availabilityImpact": "HIGH",
				"baseScore": 7.5,
				"baseSeverity": "HIGH",
				"confidentialityImpact": "NONE",
				"integrityImpact": "NONE",
				"privilegesRequired": "NONE",
				"scope": "UNCHANGED",
				"userInteraction": "NONE",
				"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
				"version": "3.1"
			},
			"exploitabilityScore": 3.9,
			"impactScore": 3.6
		}
	},
	"configurations": {
		"CVE_data_version": "4.0",
		"nodes": [
			{
				"cpe_match": [
					{
						"cpe23Uri": "cpe:2.3:a:python:pillow:*:*:*:*:*:*:*:*",
						"versionEndExcluding": "10.0.0",
						"vulnerable": true
					}
				],
				"operator": "OR"
			},
			{
				"cpe_match": [
					{
						"cpe23Uri": "cpe:2.3:o:fedoraproject:fedora:38:*:*:*:*:*:*:*",
						"vulnerable": true
					}
				],
				"operator": "OR"
			}
		]
	},
	"lastModifiedDate": "2024-11-21T08:25Z",
	"publishedDate": "2023-11-03T05:15Z"
}
