{
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "cve@mitre.org",
      "ID": "CVE-2023-41105"
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "An issue was discovered in Python 3.11 through 3.11.4. If a path containing '\\0' bytes is passed to os.path.normpath(), the path will be truncated unexpectedly at the first '\\0' byte. There are plausible cases in which an application would have rejected a filename for security reasons in Python 3.10.x or earlier, but that filename is no longer rejected in Python 3.11.x."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "CWE-426"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "https://github.com/python/cpython/pull/107982",
          "refsource": "MISC",
          "tags": [
            "Patch"
          ],
          "url": "https://github.com/python/cpython/pull/107982"
        },
        {
          "name": "https://github.com/python/cpython/pull/107983",
          "refsource": "MISC",
          "tags": [
            "Patch"
          ],
          "url": "https://github.com/python/cpython/pull/107983"
        },
        {
          "name": "https://github.com/python/cpython/pull/107981",
          "refsource": "MISC",
          "tags": [
            "Patch"
          ],
          "url": "https://github.com/python/cpython/pull/107981"
        },
        {
          "name": "https://github.com/python/cpython/issues/106242",
          "refsource": "MISC",
          "tags": [
            "Issue Tracking",
            "Patch"
          ],
          "url": "https://github.com/python/cpython/issues/106242"
        },
        {
          "name": "https://security.netapp.com/advisory/ntap-20231006-0015/",
          "refsource": "CONFIRM",
          "tags": [
            "Third Party Advisory"
          ],
          "url": "https://security.netapp.com/advisory/ntap-20231006-0015/"
        },
        {
          "name": "https://mail.python.org/archives/list/security-announce%40python.org/thread/D6CDW3ZZC5D444YGL3VQUY6D4ECMCQLD/",
          "url": "https://mail.python.org/archives/list/security-announce%40python.org/thread/D6CDW3ZZC5D444YGL3VQUY6D4ECMCQLD/"
        }
      ]
    }
  },
  "impact": {
    "baseMetricV3": {
      "cvssV3": {
        "attackComplexity": "LOW",
        "attackVector": "NETWORK",
        "availabilityImpact": "NONE",
        "baseScore": 7.5,
        "baseSeverity": "HIGH",
        "confidentialityImpact": "NONE",
        "integrityImpact": "HIGH",
        "privilegesRequired": "NONE",
        "scope": "UNCHANGED",
        "userInteraction": "NONE",
        "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
        "version": "3.1"
      },
      "exploitabilityScore": 3.9,
      "impactScore": 3.6
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "cpe_match": [
          {
            "cpe23Uri": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
            "versionEndIncluding": "3.11.4",
            "versionStartIncluding": "3.11.0",
            "vulnerable": true
          }
        ],
        "operator": "OR"
      },
      {
        "cpe_match": [
          {
            "cpe23Uri": "cpe:2.3:a:netapp:active_iq_unified_manager:-:*:*:*:*:windows:*:*",
            "vulnerable": true
          }
        ],
        "operator": "OR"
      }
    ]
  },
  "lastModifiedDate": "2023-11-07T04:20Z",
  "publishedDate": "2023-08-23T07:15Z"
}
