{
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "report@snyk.io",
      "ID": "CVE-2023-26151"
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "Versions of the package asyncua before 0.9.96 are vulnerable to Denial of Service (DoS) such that an attacker can send a malformed packet and as a result, the server will enter into an infinite loop and consume excessive memory."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "CWE-835"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "https://gist.github.com/artfire52/1540b234350795e0ecb4d672608dbec8",
          "refsource": "MISC",
          "tags": [
            "Exploit",
            "Third Party Advisory"
          ],
          "url": "https://gist.github.com/artfire52/1540b234350795e0ecb4d672608dbec8"
        },
        {
          "name": "https://github.com/FreeOpcUa/opcua-asyncio/releases/tag/v0.9.96",
          "refsource": "MISC",
          "tags": [
            "Product",
            "Release Notes"
          ],
          "url": "https://github.com/FreeOpcUa/opcua-asyncio/releases/tag/v0.9.96"
        },
        {
          "name": "https://security.snyk.io/vuln/SNYK-PYTHON-ASYNCUA-5673709",
          "refsource": "MISC",
          "tags": [
            "Exploit",
            "Patch",
            "Third Party Advisory"
          ],
          "url": "https://security.snyk.io/vuln/SNYK-PYTHON-ASYNCUA-5673709"
        },
        {
          "name": "https://github.com/FreeOpcUa/opcua-asyncio/issues/1013",
          "refsource": "MISC",
          "tags": [
            "Exploit",
            "Issue Tracking",
            "Third Party Advisory"
          ],
          "url": "https://github.com/FreeOpcUa/opcua-asyncio/issues/1013"
        },
        {
          "name": "https://github.com/FreeOpcUa/opcua-asyncio/pull/1039",
          "refsource": "MISC",
          "tags": [
            "Patch"
          ],
          "url": "https://github.com/FreeOpcUa/opcua-asyncio/pull/1039"
        },
        {
          "name": "https://github.com/FreeOpcUa/opcua-asyncio/commit/f6603daa34a93a658f0e176cb0b9ee5a6643b262",
          "refsource": "MISC",
          "tags": [
            "Patch"
          ],
          "url": "https://github.com/FreeOpcUa/opcua-asyncio/commit/f6603daa34a93a658f0e176cb0b9ee5a6643b262"
        }
      ]
    }
  },
  "impact": {
    "baseMetricV3": {
      "cvssV3": {
        "attackComplexity": "LOW",
        "attackVector": "NETWORK",
        "availabilityImpact": "HIGH",
        "baseScore": 7.5,
        "baseSeverity": "HIGH",
        "confidentialityImpact": "NONE",
        "integrityImpact": "NONE",
        "privilegesRequired": "NONE",
        "scope": "UNCHANGED",
        "userInteraction": "NONE",
        "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
        "version": "3.1"
      },
      "exploitabilityScore": 3.9,
      "impactScore": 3.6
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "cpe_match": [
          {
            "cpe23Uri": "cpe:2.3:a:freeopcua:opcua-asyncio:*:*:*:*:*:python:*:*",
            "versionEndExcluding": "0.9.96",
            "vulnerable": true
          }
        ],
        "operator": "OR"
      }
    ]
  },
  "lastModifiedDate": "2023-11-07T04:09Z",
  "publishedDate": "2023-10-03T05:15Z"
}
