{
	"cve": {
		"CVE_data_meta": {
			"ASSIGNER": "cve@mitre.org",
			"ID": "CVE-2014-1604"
		},
		"data_format": "MITRE",
		"data_type": "CVE",
		"data_version": "4.0",
		"description": {
			"description_data": [
				{
					"lang": "en",
					"value": "The parser cache functionality in parsergenerator.py in RPLY (aka python-rply) before 0.7.1 allows local users to spoof cache data by pre-creating a temporary rply-*.json file with a predictable name."
				}
			]
		},
		"problemtype": {
			"problemtype_data": [
				{
					"description": [
						{
							"lang": "en",
							"value": "NVD-CWE-Other"
						}
					]
				}
			]
		},
		"references": {
			"reference_data": [
				{
					"name": "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=735263",
					"url": "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=735263"
				},
				{
					"name": "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=735263",
					"url": "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=735263"
				},
				{
					"name": "56429",
					"tags": [
						"Vendor Advisory"
					],
					"url": "http://secunia.com/advisories/56429"
				},
				{
					"name": "56429",
					"tags": [
						"Vendor Advisory"
					],
					"url": "http://secunia.com/advisories/56429"
				},
				{
					"name": "[oss-security] 20140114 Fwd: [Python-modules-team] Bug#735263: python-rply: insecure use of /tmp",
					"url": "http://www.openwall.com/lists/oss-security/2014/01/17/8"
				},
				{
					"name": "[oss-security] 20140114 Fwd: [Python-modules-team] Bug#735263: python-rply: insecure use of /tmp",
					"url": "http://www.openwall.com/lists/oss-security/2014/01/17/8"
				},
				{
					"name": "[oss-security] 20140117 Re: Fwd: [Python-modules-team] Bug#735263: python-rply: insecure use of /tmp",
					"url": "http://www.openwall.com/lists/oss-security/2014/01/18/4"
				},
				{
					"name": "[oss-security] 20140117 Re: Fwd: [Python-modules-team] Bug#735263: python-rply: insecure use of /tmp",
					"url": "http://www.openwall.com/lists/oss-security/2014/01/18/4"
				},
				{
					"name": "102202",
					"url": "http://www.osvdb.org/102202"
				},
				{
					"name": "102202",
					"url": "http://www.osvdb.org/102202"
				},
				{
					"name": "rply-cve20141604-insecure-permissions(90593)",
					"url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/90593"
				},
				{
					"name": "rply-cve20141604-insecure-permissions(90593)",
					"url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/90593"
				},
				{
					"name": "https://github.com/alex/rply/commit/fc9bbcd25b0b4f09bbd6339f710ad24c129d5d7c",
					"url": "https://github.com/alex/rply/commit/fc9bbcd25b0b4f09bbd6339f710ad24c129d5d7c"
				},
				{
					"name": "https://github.com/alex/rply/commit/fc9bbcd25b0b4f09bbd6339f710ad24c129d5d7c",
					"url": "https://github.com/alex/rply/commit/fc9bbcd25b0b4f09bbd6339f710ad24c129d5d7c"
				}
			]
		}
	},
	"impact": {
		"baseMetricV2": {
			"cvssV2": {
				"accessComplexity": "LOW",
				"accessVector": "LOCAL",
				"authentication": "NONE",
				"availabilityImpact": "NONE",
				"baseScore": 2.1,
				"confidentialityImpact": "NONE",
				"integrityImpact": "PARTIAL",
				"vectorString": "AV:L/AC:L/Au:N/C:N/I:P/A:N",
				"version": "2.0"
			},
			"exploitabilityScore": 3.9,
			"impactScore": 2.9,
			"severity": "LOW"
		}
	},
	"configurations": {
		"CVE_data_version": "4.0",
		"nodes": [
			{
				"cpe_match": [
					{
						"cpe23Uri": "cpe:2.3:a:python:rply:*:*:*:*:*:*:*:*",
						"versionEndIncluding": "0.7.0",
						"vulnerable": true
					}
				],
				"operator": "OR"
			}
		]
	},
	"lastModifiedDate": "2024-11-21T02:04Z",
	"publishedDate": "2014-01-28T00:55Z"
}
