{
	"cve": {
		"CVE_data_meta": {
			"ASSIGNER": "cve@mitre.org",
			"ID": "CVE-2022-47515"
		},
		"data_format": "MITRE",
		"data_type": "CVE",
		"data_version": "4.0",
		"description": {
			"description_data": [
				{
					"lang": "en",
					"value": "An issue was discovered in drachtio-server before 0.8.20. It allows remote attackers to cause a denial of service (daemon crash) via a long message in a TCP request that leads to std::length_error."
				}
			]
		},
		"problemtype": {
			"problemtype_data": [
				{
					"description": [
						{
							"lang": "en",
							"value": "NVD-CWE-noinfo"
						}
					]
				}
			]
		},
		"references": {
			"reference_data": [
				{
					"name": "https://github.com/drachtio/drachtio-server/commit/4cf9fe2c420b86c16442215d449d40be777c1911",
					"tags": [
						"Patch",
						"Third Party Advisory"
					],
					"url": "https://github.com/drachtio/drachtio-server/commit/4cf9fe2c420b86c16442215d449d40be777c1911"
				},
				{
					"name": "https://github.com/drachtio/drachtio-server/commit/4cf9fe2c420b86c16442215d449d40be777c1911",
					"tags": [
						"Patch",
						"Third Party Advisory"
					],
					"url": "https://github.com/drachtio/drachtio-server/commit/4cf9fe2c420b86c16442215d449d40be777c1911"
				},
				{
					"name": "https://github.com/drachtio/drachtio-server/issues/245",
					"tags": [
						"Exploit",
						"Third Party Advisory"
					],
					"url": "https://github.com/drachtio/drachtio-server/issues/245"
				},
				{
					"name": "https://github.com/drachtio/drachtio-server/issues/245",
					"tags": [
						"Exploit",
						"Third Party Advisory"
					],
					"url": "https://github.com/drachtio/drachtio-server/issues/245"
				}
			]
		}
	},
	"impact": {
		"baseMetricV3": {
			"cvssV3": {
				"attackComplexity": "LOW",
				"attackVector": "NETWORK",
				"availabilityImpact": "HIGH",
				"baseScore": 7.5,
				"baseSeverity": "HIGH",
				"confidentialityImpact": "NONE",
				"integrityImpact": "NONE",
				"privilegesRequired": "NONE",
				"scope": "UNCHANGED",
				"userInteraction": "NONE",
				"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
				"version": "3.1"
			},
			"exploitabilityScore": 3.9,
			"impactScore": 3.6
		}
	},
	"configurations": {
		"CVE_data_version": "4.0",
		"nodes": [
			{
				"cpe_match": [
					{
						"cpe23Uri": "cpe:2.3:a:drachtio:drachtio-server:*:*:*:*:*:*:*:*",
						"versionEndExcluding": "0.8.20",
						"vulnerable": true
					}
				],
				"operator": "OR"
			}
		]
	},
	"lastModifiedDate": "2024-11-21T07:32Z",
	"publishedDate": "2022-12-18T05:15Z"
}
